django/myproject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, SignUpSuccessView, UserUpdateView, get_csrf, login_view, logout_view, session_view, whoami_view

app_name = 'accounts'

urlpatterns = [
    path('signup/',
         SignUpView.as_view(), name='signup'),

    path('signup_success/',
         SignUpSuccessView.as_view(), name='signup_success'),

    path('login/',
         auth_views.LoginView.as_view(template_name="login.html"), name='login'),

    path('logout/',
         auth_views.LogoutView.as_view(template_name="logout.html"), name='logout'),

    # ユーザー情報を更新
    path('update/<int:pk>/',
         UserUpdateView.as_view(), name='update'),

    # react用
    path('accounts/csrf/', get_csrf, name='react-csrf'),
    path('accounts/login/', login_view, name='react-login'),
    path('accounts/logout/', logout_view, name='react-logout'),
    path('accounts/session/', session_view, name='react-session'),
    path('accounts/whoami/', whoami_view, name='react-whoami'),
]

django/myproject/app/urls.py
from django.urls import path

from .views.category import *
from .views.index import *
from .views.like import *
from .views.narrow import *
from .views.twitter_view import update_twitter_post
from .views.visit import *

app_name = 'app'

urlpatterns = [
    # トップページ
    path('', IndexView.as_view(), name='index'),

    # 検索
    path('search_index/', IndexSearchView.as_view(), name='search_index'),

    # ワールド投稿取得
    path('twitter/recent/', update_twitter_post, name='recent'),

    # お気に入り
    path('like/', like_view, name='like'),

    # 訪問済み
    path('visit/', visit_view, name='visit'),

    # カテゴリ
    # カテゴリ変更
    path('category/change/', change_category_view, name='change_category'),

    # new
    path('category/new/', new_category_view, name='new_category'),

    # カテゴリ作成取りやめ
    path('category/back/', back_category_view, name='back_category'),

    # create
    path('category/create/', create_category_view, name='create_category'),

    # edit
    path('category/edit/', edit_category_view, name='edit_category'),

    # delete
    path('category/delete/', delete_category_view, name='delete_category'),

    # update
    path('category/update/', update_category_view, name='update_category'),

    # モーダル
    path('narrow/', narrow_view, name='narrow'),
]

django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from accounts.views import CustomPasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),

    # app用urls
    path('', include('app.urls')),

    # accounts用
    path('', include('accounts.urls')),

    # パスワードリセット関連
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name="password_reset.html"), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="password_reset_sent.html"), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password_reset_form.html"), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="password_reset_done.html"), name='password_reset_complete'),
]

django/myproject/app/views/category.py
"""
カテゴリ関連機能のview
"""
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from ..models import TwitterCategory, TwitterLike, TwitterPost


@login_required
def change_category_view(request):
    if request.method == "POST":
        get_id = int(request.POST.get("twitter_post_id"))
        get_category_id = int(request.POST.get("selected_category_id"))

        twitter_post = get_object_or_404(TwitterPost, pk=get_id)
        user = request.user

        like = TwitterLike.objects.filter(twitter_post=twitter_post, user=user).first()

        categories = TwitterCategory.objects.filter(user=user).values_list("id", flat=True)

        if get_category_id not in categories:
            like.category = None
            like.save()
        else:
            like.category = TwitterCategory.objects.filter(user=user, id=get_category_id).first()
            like.save()

        context = {
            "record": twitter_post,
            "category_objects": TwitterCategory.objects.filter(user=user),
            "liked_objects": TwitterLike.objects.filter(user=user)
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="category.html", context=context)


@login_required
def new_category_view(request):
    if request.method == "POST":

        get_id = int(request.POST.get("twitter_post_id"))

        twitter_post = get_object_or_404(TwitterPost, pk=get_id)

        context = {
            "record": twitter_post
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="category_new.html", context=context)


@login_required
def back_category_view(request):
    if request.method == "POST":

        get_id = int(request.POST.get("twitter_post_id"))

        twitter_post = get_object_or_404(TwitterPost, pk=get_id)
        user = request.user

        context = {
            "record": twitter_post,
            "category_objects": TwitterCategory.objects.filter(user=user),
            "liked_objects": TwitterLike.objects.filter(user=user)
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="category.html", context=context)


@login_required
def create_category_view(request):
    if request.method == "POST":

        get_id = int(request.POST.get("twitter_post_id"))
        new_category_name = request.POST.get("new_category_name")

        twitter_post = get_object_or_404(TwitterPost, pk=get_id)
        user = request.user

        # カテゴリが存在するかを確認
        exist_check = TwitterCategory.objects.filter(user=user, category=new_category_name).first()

        if exist_check is not None or new_category_name == "":
            raise Exception("既に存在するカテゴリです")
        else:
            new_category = TwitterCategory.objects.create(user=user, category=new_category_name)
            twitter_like = TwitterLike.objects.filter(user=user, twitter_post=twitter_post).first()
            twitter_like.category = new_category
            twitter_like.save()

        context = {
            "record": twitter_post,
            "category_objects": TwitterCategory.objects.filter(user=user),
            "liked_objects": TwitterLike.objects.filter(user=user)
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="category.html", context=context)


@login_required
def edit_category_view(request):
    if request.method == "POST":

        get_id = int(request.POST.get("twitter_post_id"))

        twitter_post = get_object_or_404(TwitterPost, pk=get_id)
        user = request.user
        liked = TwitterLike.objects.filter(user=user, twitter_post=twitter_post).first()

        context = {
            "record": twitter_post,
            "liked": liked
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="category_edit.html", context=context)


@login_required
def delete_category_view(request):
    if request.method == "POST":

        get_id = int(request.POST.get("twitter_post_id"))

        twitter_post = get_object_or_404(TwitterPost, pk=get_id)
        user = request.user

        liked = TwitterLike.objects.filter(user=user, twitter_post=twitter_post).first()

        delete_category = liked.category

        if delete_category is None or delete_category == "":
            raise Exception("存在しないカテゴリです")
        else:
            delete_category.delete()

        context = {
            "record": twitter_post,
            "category_objects": TwitterCategory.objects.filter(user=user),
            "liked_objects": TwitterLike.objects.filter(user=user)
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="category.html", context=context)


@login_required
def update_category_view(request):
    if request.method == "POST":

        get_id = int(request.POST.get("twitter_post_id"))
        update_category_name = request.POST.get("update_category_name")

        twitter_post = get_object_or_404(TwitterPost, pk=get_id)
        user = request.user

        # カテゴリが存在するかを確認
        exist_check = TwitterCategory.objects.filter(user=user, category=update_category_name).first()

        if exist_check is not None or update_category_name == "":
            raise Exception("既に存在するカテゴリです")
        else:
            update_category = TwitterLike.objects.filter(user=user, twitter_post=twitter_post).first().category
            update_category.category = update_category_name

            update_category.save()

        context = {
            "record": twitter_post,
            "category_objects": TwitterCategory.objects.filter(user=user),
            "liked_objects": TwitterLike.objects.filter(user=user)
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="category.html", context=context)

django/myproject/app/views/like.py
"""
お気に入り機能のview
"""
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from ..models import TwitterCategory, TwitterLike, TwitterPost


@login_required
def like_view(request):
    if request.method == "POST":
        twitter_post = get_object_or_404(TwitterPost, pk=request.POST.get("twitter_post_id"))
        user = request.user
        like = TwitterLike.objects.filter(twitter_post=twitter_post, user=user)

        if like.exists():
            like.delete()
        else:
            like.create(twitter_post=twitter_post, user=user)

        context = {
            "twitter_post_id": twitter_post.id,
            "record": twitter_post,
            "liked_list": list(TwitterLike.objects.filter(user=user).values_list("twitter_post", flat=True)),
            "category_objects": TwitterCategory.objects.filter(user=user),
            "liked_objects": TwitterLike.objects.filter(user=user)
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="like.html", context=context)

django/myproject/app/views/narrow.py
"""
絞り込み機能のview
"""
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from ..models import TwitterCategory


@login_required
def narrow_view(request):
    if request.method == "GET":

        user = request.user

        context = {
            "category_objects": TwitterCategory.objects.filter(user=user)
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":

        return render(request, template_name="narrow.html", context=context)

django/myproject/app/views/visit.py
"""
訪問済み機能のview
"""
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from ..models import TwitterPost, TwitterVisit


@login_required
def visit_view(request):
    if request.method == "POST":
        get_id = int(request.POST.get("twitter_post_id").replace("visit_", ""))
        twitter_post = get_object_or_404(TwitterPost, pk=get_id)
        user = request.user
        visited = False
        visit = TwitterVisit.objects.filter(twitter_post=twitter_post, user=user)

        if visit.exists():
            visit.delete()
        else:
            visit.create(twitter_post=twitter_post, user=user)
            visited = True

        context = {
            "twitter_post_id": twitter_post.id,
            "visited": visited,
        }

    if request.headers.get("x-requested-with") == "XMLHttpRequest":
        return JsonResponse(context)

django/myproject/app/templates/base.html
<!--静的ファイルをロード-->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-0HKNDPJJ35"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-0HKNDPJJ35');
        </script>
        <!-- Google tag (gtag.js) -->

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://kit.fontawesome.com/dd887dba69.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand text-white" href={% url 'app:index' %}>VRChat World Recommender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link  text-white" aria-current="page" href={% url 'app:index' %}>トップページ</a></li>
                        
                        {% if user.is_authenticated %}

                            <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:update' pk=user.pk %}">マイページ</a></li>
                            <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:logout' %}">ログアウト</a></li>
                        
                        {% else %}

                            <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:signup' %}">サインアップ</a></li>
                            <li class="nav-item"><a class="nav-link text-white" href="{% url 'accounts:login' %}">ログイン</a></li>
                        
                        {% endif %}

                    </ul>
                    {% if request.user.is_staff %}
                        <a class="btn btn-outline-dark text-white" href="{% url 'app:recent' %}">データ更新</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <!-- Header-->
        {% block header %}{% endblock %}
        <!-- Section-->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="py-4 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; VRChat World Recommender 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
    </body>
</html>

django/myproject/app/templates/category.html
<!-- カテゴリプルダウン-->

{% load twitter_like_tags %}
<div class="d-flex">
    <select id="category-dropdown" name="category-select_{{record.id}}" class="form-select own-select-width" style="font-size: 0.75rem; font-weight: bold;" title="カテゴリ設定">

        <!-- 空カテゴリを追加-->
        {% if liked_objects|return_category:record is None %}
            <option value="-1" selected>-</option>
        {% else %}
            <option value="-1">-</option>
        {% endif %}

        {% for category_object in category_objects %}
            {% if category_object == liked_objects|return_category:record %}
                <option value="{{category_object.id}}" selected>{{category_object.category}}</option>
            {% else %}
                <option value="{{category_object.id}}">{{category_object.category}}</option>
            {% endif %}
        {% endfor %}

    </select>

    <button id="category-new" name="category-new_{{record.id}}" class="btn own-like-padding" title="カテゴリ追加">
        <i class="fa-solid fa-plus"></i>
    </button>

    <!-- 空カテゴリ以外では編集ボタンを表示-->
    {% if liked_objects|return_category:record is not None %}
        <button id="category-edit" name="category-edit_{{record.id}}" class="btn own-like-padding" title="カテゴリ編集">
            <i class="fa-solid fa-pen-to-square"></i>
        </button>
    {% endif %}
</div>

django/myproject/app/templates/category_edit.html
<!-- カテゴリ編集-->

<div class="d-flex">
    <input id="edit-category-input_{{record.id}}" type="search" name="edit-category" class="own-select-width-no-visit" value="{{liked.category}}">

    <button id="update-category" name="edit-category_{{record.id}}" type="button" class="btn own-like-padding" title="保存">
        <i class="fa-solid fa-floppy-disk"></i>
    </button>

    <button id="delete-category" name="delete-category_{{record.id}}" class="btn own-like-padding" title="削除">
        <i class="fa-solid fa-trash"></i>
    </button>

    <button id="back-category" name="back-category_{{record.id}}" class="btn own-like-padding" title="戻る">
        <i class="fa-solid fa-reply"></i>
    </button>
</div>

django/myproject/app/templates/category_new.html
<!-- カテゴリ登録-->

<div class="d-flex">
    <input id="create-category-input_{{record.id}}" type="search" name="new-category" class="own-select-width-no-visit" placeholder="カテゴリ入力">

    <button id="create-category" name="create-category_{{record.id}}" type="button" class="btn own-like-padding" title="保存">
        <i class="fa-solid fa-floppy-disk"></i>
    </button>

    <button id="back-category" name="back-category_{{record.id}}" class="btn own-like-padding" title="戻る">
        <i class="fa-solid fa-reply"></i>
    </button>
</div>

django/myproject/app/templates/contents.html
<!--twitter投稿の一覧-->
{% load twitter_content_tags %}

<section class="px-6 pb-5">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 row-cols-xxl-6 justify-content-center"> 

        {% for record in orderby_records %}
            <div name="twitter-post" class="align-items-center">
                
                <!--twitter投稿-->
                {% if forloop.counter == 1 %}
                    {{record.emb_html | safe}}
                {% else %}
                    {{record.emb_html | remove_script | safe}}
                {% endif %}

                <!--ログイン時のみ各種ボタンを表示する-->
                {% if not request.user.is_anonymous %}
                    <div class="d-flex justify-content-center gap-2 flex-wrap pb-5">
                        
                        <!--訪問済みボタン-->
                        {% include 'visit.html' %}
                        
                        <!--お気に入りボタン-->
                        <div name="user_like_{{record.id}}">
                            {% include 'like.html' %}
                        </div>

                    </div>
                {% endif %}

            </div>
        {% endfor %}

    </div>
</section>

<!--ページネーション-->
{% include "pagination.html" %}

django/myproject/app/templates/like.html
<!-- お気に入り・カテゴリボタン-->

<form action="{% url 'app:like' %}" method="POST">

    {% csrf_token %}

    <!-- お気に入り済みかを確認-->
    {% if record.id in liked_list %}
        <div class="d-flex justify-content-center gap-2 flex-wrap align-items-center">
            
            <!-- お気に入りボタン-->
            <button id="like" name="{{record.id}}" class="btn btn-outline-dark own-like-padding" title="お気に入り登録済み">
                <i class="fa-solid fa-star" style="color:#FFCC00"></i>
            </button>

            <!-- カテゴリプルダウン-->
            <div id="like_category" name="like_category_{{record.id}}">
                {% include "category.html" %}
            </div> 

        </div>
    {% else %}
        <div class="d-flex justify-content-center gap-2 flex-wrap align-items-center">
            
            <!-- お気に入りボタン-->
            <button id="like" name="{{record.id}}" class="btn btn-outline-dark own-like-padding" title="お気に入りに登録">
                <i class="fa-regular fa-star"></i>
            </button>

            <!-- カテゴリプルダウン-->
            <div id="like_category" name="like_category_{{record.id}}"></div>

        </div>
    {% endif %}
</form>

django/myproject/app/templates/narrow.html
<!-- 絞り込み機能-->
<div class="modal-body">

    <!-- モーダルを閉じるボタン-->
    <div id="modal-close" class="modal-close">×</div>

    <!-- モーダル-->
    <div class="modal-content">
        <p class="own-lead-form pb-3">絞り込み</p>

        <form id="narrow-form" class="own-form">

            <!-- 範囲絞り込み-->
            <div id="narrow-range" class="own-item">
                <p class="own-label">範囲</p>
                <label>
                    <input id="narrow-all" type="radio" name="narrow-radio" value="all" checked="checked">
                    全て
                </label>
                <label>
                    <input id="narrow-like" type="radio" name="narrow-radio" value="like">
                    お気に入り
                </label>
                <label>
                    <input id="narrow-visit" type="radio" name="narrow-radio" value="visit">
                    訪問済み
                </label>
            </div>

            <!-- カテゴリ絞り込み-->
            <div class="own-item">
                <p class="own-label">カテゴリ</p>

                <div id="narrow-category" class="own-inputs">

                    <!-- ユーザーのカテゴリ一覧を表示-->
                    {% for category in category_objects %}
                        <label>
                            <input type="checkbox" class="own-input-test" name="narrow-category" value="{{category.id}}">
                            {{category.category}}
                        </label>
                    {% endfor %}

                </div>

            </div>

        </form>
    </div>
</div>

django/myproject/app/templates/pagination.html
<!-- ページネーション-->
<ul class="pagination"
    style="justify-content:center">
    
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link"
                href="?search_word={{search_word}}&paginate_by={{ paginate_by }}&page={{ page_obj.previous_page_number }}"
                aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}
    
    {% for num in page_obj.paginator.page_range %}
        {% if num <= page_obj.number|add:10 and num >= page_obj.number|add:-10 %}

            {% if page_obj.number == num %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?search_word={{search_word}}&paginate_by={{ paginate_by }}&page={{ num }}">{{ num }}</a>
                </li>
            {% endif %}
            
        {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
                href="?search_word={{search_word}}&paginate_by={{ paginate_by }}&page={{ page_obj.next_page_number }}"
                aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
</ul>

django/myproject/app/templates/visit.html
<!-- 訪問済み機能-->
<form action="{% url 'app:visit' %}" method="POST">

    {% csrf_token %}
    
    {% if record.id in visited_list %}
        <button id="visit" name="visit_{{record.id}}" class="btn btn-outline-dark own-visit-padding" title="訪問済み">
            <i class="fa-solid fa-calendar-check" title="訪問済み"></i>
        </button>
    {% else %}
        <button id="visit" name="visit_{{record.id}}" class="btn btn-outline-dark own-visit-padding" title="未訪問">
            <i class="fa-solid fa-calendar-minus" title="未訪問"></i>
        </button>
    {% endif %}

</form>